/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphemployee;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Arrays;

/**
 *
 * @author set
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    private String employeeNumber;
    
    public Dashboard(String employeeNumber) {
        this.employeeNumber = employeeNumber;
        initComponents();
        displayEmployeeData();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_employee_number1 = new javax.swing.JLabel();
        txt_birthday = new javax.swing.JLabel();
        txt_phone = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_address = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_sss = new javax.swing.JLabel();
        txt_philhealth = new javax.swing.JLabel();
        txt_tin = new javax.swing.JLabel();
        txt_pagibig = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_supervisor = new javax.swing.JLabel();
        txt_status = new javax.swing.JLabel();
        txt_position = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_hourly_rate = new javax.swing.JLabel();
        txt_basic_salary = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        button_view_salary = new javax.swing.JButton();
        button_leave_form = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();
        button_edit_information = new javax.swing.JButton();
        button_change = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txt_position3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txt_position2 = new javax.swing.JLabel();
        txt_leaveCredits = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txt_position4 = new javax.swing.JLabel();
        txt_approvedLeaves = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txt_position5 = new javax.swing.JLabel();
        txt_rejectedLeaves = new javax.swing.JLabel();
        txt_position1 = new javax.swing.JLabel();
        txt_first_name = new javax.swing.JLabel();
        txt_last_name = new javax.swing.JLabel();
        txt_status1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txt_rice_subsidy3 = new javax.swing.JLabel();
        txt_phone_allowance3 = new javax.swing.JLabel();
        txt_clothing_allowance3 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/avatar.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 33, 33), 3));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MotorPH logo.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel26.setText("MotorPH Employee Management Payroll System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Personal Information");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel8.setText("Employee Number");
        jLabel8.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel10.setText("Birthday");
        jLabel10.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel12.setText("Address");
        jLabel12.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel14.setText("Phone Number");
        jLabel14.setEnabled(false);

        txt_employee_number1.setText("Employee Number");

        txt_birthday.setText("Birthday");

        txt_phone.setText("Phone Number");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/address.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/employee_number.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/birthday-cake.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/telephone.png"))); // NOI18N

        txt_address.setText("Address");
        txt_address.setFocusTraversalKeysEnabled(false);
        txt_address.setFocusable(false);
        txt_address.setInheritsPopupMenu(false);
        txt_address.setRequestFocusEnabled(false);
        txt_address.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_employee_number1)
                            .addComponent(jLabel10)
                            .addComponent(txt_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_employee_number1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_birthday)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_address)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_phone)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14))
                    .addComponent(jLabel11))
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Tax Information");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel18.setText("SSS");
        jLabel18.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel20.setText("Philhealth");
        jLabel20.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel22.setText("TIN");
        jLabel22.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel23.setText("Pag-ibig");
        jLabel23.setEnabled(false);

        txt_sss.setText("SSS");

        txt_philhealth.setText("Philhealth");

        txt_tin.setText("TIN");

        txt_pagibig.setText("Pag-ibig");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_pagibig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_tin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_sss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_philhealth, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txt_sss)
                .addGap(0, 0, 0)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txt_philhealth)
                .addGap(0, 0, 0)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(txt_tin)
                .addGap(0, 0, 0)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(txt_pagibig)
                .addGap(0, 0, 0)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Great to have you here, ");

        jLabel5.setText("Work hard, stay focused, and never give up. Your dedication will pay off.");
        jLabel5.setEnabled(false);

        txt_firstname.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txt_firstname.setText("First Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txt_firstname))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_firstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setPreferredSize(new java.awt.Dimension(210, 207));

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("Employement Status");

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel30.setText("Status");
        jLabel30.setEnabled(false);

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel32.setText("Position");
        jLabel32.setEnabled(false);

        txt_supervisor.setText("Supervisor");

        txt_status.setText("Status");

        txt_position.setText("Position");

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel37.setText("Supervisor");
        jLabel37.setEnabled(false);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/signature.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/supervisor.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/position.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(txt_supervisor)
                            .addComponent(txt_status)
                            .addComponent(txt_position)
                            .addComponent(jLabel37)))
                    .addComponent(jLabel25))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_status)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel30))
                    .addComponent(jLabel21))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_position)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel32)
                        .addGap(30, 30, 30)
                        .addComponent(txt_supervisor)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel37))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel28.setText("Salary Information");

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel42.setText("Basic Salary");
        jLabel42.setEnabled(false);

        txt_hourly_rate.setText("Hourly Rate");

        txt_basic_salary.setText("Basic Salary");

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel46.setText("Hourly Rate");
        jLabel46.setEnabled(false);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/bill.png"))); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/working-hour.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel39))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_basic_salary)
                            .addComponent(jLabel42)
                            .addComponent(txt_hourly_rate)
                            .addComponent(jLabel46)))
                    .addComponent(jLabel28))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_basic_salary)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel42))
                    .addComponent(jLabel33))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_hourly_rate)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel46))
                    .addComponent(jLabel39))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(244, 69, 69));

        button_view_salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salary.png"))); // NOI18N
        button_view_salary.setText("View Salary");
        button_view_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_view_salaryActionPerformed(evt);
            }
        });

        button_leave_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/form.png"))); // NOI18N
        button_leave_form.setText("Leave Form");
        button_leave_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_leave_formActionPerformed(evt);
            }
        });

        button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        button_exit.setText("Exit");
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        button_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        button_logout.setText("Log-out");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        button_edit_information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pen.png"))); // NOI18N
        button_edit_information.setText("Edit Information");
        button_edit_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_informationActionPerformed(evt);
            }
        });

        button_change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/information.png"))); // NOI18N
        button_change.setText("Change Credentials");
        button_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_edit_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_view_salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_leave_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(button_edit_information)
                .addGap(18, 18, 18)
                .addComponent(button_view_salary)
                .addGap(18, 18, 18)
                .addComponent(button_leave_form)
                .addGap(18, 18, 18)
                .addComponent(button_change)
                .addGap(18, 18, 18)
                .addComponent(button_logout)
                .addGap(18, 18, 18)
                .addComponent(button_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        time.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        time.setText("Time");
        time.setToolTipText("");

        date.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        date.setText("Date");
        date.setToolTipText("");

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_position3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txt_position3.setText("Leave Approval");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_position2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_position2.setText("Leave Credits");

        txt_leaveCredits.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_leaveCredits.setForeground(new java.awt.Color(209, 33, 33));
        txt_leaveCredits.setText("Number");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_position2)
                    .addComponent(txt_leaveCredits))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_position2)
                .addGap(32, 32, 32)
                .addComponent(txt_leaveCredits)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_position4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_position4.setText("Approved Leaves");

        txt_approvedLeaves.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_approvedLeaves.setForeground(new java.awt.Color(209, 33, 33));
        txt_approvedLeaves.setText("Number");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_position4)
                    .addComponent(txt_approvedLeaves))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_position4)
                .addGap(32, 32, 32)
                .addComponent(txt_approvedLeaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_position5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_position5.setText("Rejected Leaves");

        txt_rejectedLeaves.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_rejectedLeaves.setForeground(new java.awt.Color(209, 33, 33));
        txt_rejectedLeaves.setText("Number");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_position5)
                    .addComponent(txt_rejectedLeaves))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_position5)
                .addGap(32, 32, 32)
                .addComponent(txt_rejectedLeaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_position3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_position3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_position1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_position1.setText("Position");

        txt_first_name.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        txt_first_name.setText("First Name");

        txt_last_name.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        txt_last_name.setText("Last Name");

        txt_status1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_status1.setText("Status");

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 205));

        jLabel57.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel57.setText("Benefits");

        jLabel58.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel58.setText("Rice Subsidy");
        jLabel58.setEnabled(false);

        jLabel59.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel59.setText("Phone Allowance");
        jLabel59.setEnabled(false);

        jLabel60.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel60.setText("Clothing Allowance");
        jLabel60.setEnabled(false);

        txt_rice_subsidy3.setText("Rice Subsidy");

        txt_phone_allowance3.setText("Phone Allowance");

        txt_clothing_allowance3.setText("Clothing Allowance");

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/t-shirt.png"))); // NOI18N

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/smartphone.png"))); // NOI18N

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/rice.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel62)
                                .addComponent(jLabel63))
                            .addComponent(jLabel61))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59)
                            .addComponent(txt_rice_subsidy3)
                            .addComponent(txt_clothing_allowance3)
                            .addComponent(txt_phone_allowance3)))
                    .addComponent(jLabel57))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(txt_rice_subsidy3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel58))
                    .addComponent(jLabel63))
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(txt_phone_allowance3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel59))
                    .addComponent(jLabel62))
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(txt_clothing_allowance3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel60))
                    .addComponent(jLabel61))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date)
                            .addComponent(time)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_first_name)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_last_name))
                                .addComponent(txt_position1)
                                .addComponent(txt_status1))
                            .addGap(30, 30, 30)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date))
                            .addComponent(jLabel26))))
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_first_name)
                                    .addComponent(txt_last_name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_position1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_status1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        // Exit the application
        System.exit(0);
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_view_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_view_salaryActionPerformed
        // TODO add your handling code here:
        String csvFilePath = "src/motorphemployee/data.csv";
        
    try (BufferedReader reader = new BufferedReader(new FileReader(csvFilePath))) {
    String line;
    boolean found = false;

    // Variables to hold employee data
    String lastName = "";
    String firstName = "";
    String birthday = "";
    String address = "";
    String phoneNumber = "";
    String sssNumber = "";
    String philhealthNumber = "";
    String tinNumber = "";
    String pagibigNumber = "";
    String status = "";
    String position = "";
    String supervisor = "";
    String basicSalaryStr = "";
    String riceSubsidyStr = "";
    String phoneAllowanceStr = "";
    String clothingAllowanceStr = "";
    String grossSemiMonthlyRateStr = "";
    String hourlyRateStr = "";
    
    // Read the CSV file
    while ((line = reader.readLine()) != null) {
        String[] parts = line.split(",");
        if (parts.length >= 21 && parts[0].trim().equals(employeeNumber)) {
             // Assign employee data to variables
            lastName = parts[1].trim();
            firstName = parts[2].trim();
            birthday = parts[3].trim();
            address = parts[4].trim();
            phoneNumber = parts[5].trim();
            sssNumber = parts[6].trim();
            philhealthNumber = parts[7].trim();
            tinNumber = parts[8].trim();
            pagibigNumber = parts[9].trim();
            status = parts[10].trim();
            position = parts[11].trim();
            supervisor = parts[12].trim();
            basicSalaryStr = parts[13].trim();
            riceSubsidyStr = parts[14].trim();
            phoneAllowanceStr = parts[15].trim();
            clothingAllowanceStr = parts[16].trim();
            grossSemiMonthlyRateStr = parts[17].trim();
            hourlyRateStr = parts[18].trim();
            found = true;
            break;
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(null, "Employee not found for Employee Number: " + employeeNumber);
    } else {
        // Convert string to double
        double hourlyRate = Double.parseDouble(hourlyRateStr);

        // Array of months
        String[] months = {
            "January", "February", "March", "April",
            "May", "June", "July", "August",
            "September", "October", "November", "December"
        };

        // Array of number of working days corresponding to each month
        int[] workingDays = {
            23, 21, 21, 22,
            23, 20, 23, 22,
            21, 23, 21, 22
        };

        // Let the user choose the month
        String selectedMonth = (String) JOptionPane.showInputDialog(
                this,
                "Choose a month:",
                "Month Selection",
                JOptionPane.PLAIN_MESSAGE,
                null,
                months,
                null
        );

        if (selectedMonth != null) { // If user selects a month
            // Retrieve the number of working days for the selected month
            int index = Arrays.asList(months).indexOf(selectedMonth);
            int workedDays = workingDays[index];

            // Calculate total salary
            double totalSalary = workedDays * hourlyRate * 8; // Assuming working 8 hours a day

            // Call SSS, PhilHealth, Pagibig methods
            double sssContribution = calculateSSSContribution(totalSalary);
            double philhealthContribution = calculatePhilHealthContribution(totalSalary);
            double pagibigContribution = calculatePagibigContribution(totalSalary);

            // Calculate total deductions without WithHolding Tax
            double grossDeductions = sssContribution + philhealthContribution + pagibigContribution;

            // Calculate Salary After Tax
            double salaryAfterTax = totalSalary - grossDeductions;

            // Call Withholding Tax methods
            double withholdingTax = calculateWithholdingTax(salaryAfterTax);

            // Calculate total deductions
            double totalDeductions = grossDeductions + withholdingTax;

            // Calculate Net Pay
            double netPay = salaryAfterTax - withholdingTax;

            // Display salary and deductions in a dialog
            String message = "Employee Information:\n";
            message += "Name: " + firstName + " " + lastName + "\n";
            message += "Birthday: " + birthday + "\n";
            message += "Address: " + address + "\n";
            message += "Phone Number: " + phoneNumber + "\n";
            message += "SSS: " + sssNumber + "\n";
            message += "PhilHealth: " + philhealthNumber + "\n";
            message += "TIN: " + tinNumber + "\n";
            message += "Pagibig: " + pagibigNumber + "\n";
            message += "Status: " + status + "\n";
            message += "Position: " + position + "\n";
            message += "Supervisor: " + supervisor + "\n";
            message += "Basic Salary: " + basicSalaryStr + "\n";
            message += "Rice Subsidy: " + riceSubsidyStr + "\n";
            message += "Phone Allowance: " + phoneAllowanceStr + "\n";
            message += "Clothing Allowance: " + clothingAllowanceStr + "\n";
            message += "Gross Semi-Monthly Rate: " + grossSemiMonthlyRateStr + "\n";
            message += "Hourly Rate: " + hourlyRateStr + "\n\n";
            message += "Salary Details for " + selectedMonth + ":\n";
            message += "Worked Days: " + workedDays + "\n";
            message += "Gross Salary: PHP " + String.format("%.2f", totalSalary) + "\n";
            message += "SSS Contribution: PHP " + String.format("%.2f", sssContribution) + "\n";
            message += "PhilHealth Contribution: PHP " + String.format("%.2f", philhealthContribution) + "\n";
            message += "Pagibig Contribution: PHP " + String.format("%.2f", pagibigContribution) + "\n";
            message += "Withholding Tax: PHP " + String.format("%.2f", withholdingTax) + "\n";
            message += "Total Deductions: PHP " + String.format("%.2f", totalDeductions) + "\n";
            message += "Net Pay: PHP " + String.format("%.2f", netPay) + "\n";

            JOptionPane.showMessageDialog(this, message);
        } else {
        }
    }
} catch (IOException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error reading employee data. Please try again later.");
}

        
        
    }//GEN-LAST:event_button_view_salaryActionPerformed

    private void button_leave_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_leave_formActionPerformed
        // TODO add your handling code here:
    LeaveForm leaveForm = new LeaveForm(employeeNumber);
    
    // Make the LeaveForm visible
    leaveForm.setVisible(true);
    
    }//GEN-LAST:event_button_leave_formActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        // TODO add your handling code here:                                          
    // Ask user if they are sure to log out
    int option = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log Out", javax.swing.JOptionPane.YES_NO_OPTION);

    // Check user's choice
    if (option == javax.swing.JOptionPane.YES_OPTION) {
        // Proceed with logout
        Login logIn = new Login();
        logIn.setVisible(true);
        this.dispose(); // Close the current window
    }        
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_edit_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_informationActionPerformed
        // TODO add your handling code here:
         javax.swing.JOptionPane.showMessageDialog(null, "Please contact your HR to edit your information.");
    }//GEN-LAST:event_button_edit_informationActionPerformed

    private void button_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_changeActionPerformed
        // TODO add your handling code here:
        ChangeCredentials changeCredentials = new ChangeCredentials(employeeNumber);
    
   
        changeCredentials.setVisible(true);
        
    }//GEN-LAST:event_button_changeActionPerformed

    private void displayEmployeeData() {
        
    String csvFilePath = "src/motorphemployee/data.csv";

    try (BufferedReader reader = new BufferedReader(new FileReader(csvFilePath))) {
        String line;
        boolean found = false;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length >= 21 && parts[0].trim().equals(employeeNumber)) {
                 // Set UI components with employee data
                String lastName = parts[1].trim();
                String firstName = parts[2].trim();
                String birthday = parts[3].trim();
                String address = parts[4].trim();
                String phoneNumber = parts[5].trim();
                String sssNumber = parts[6].trim();
                String philhealthNumber = parts[7].trim();
                String tinNumber = parts[8].trim();
                String pagibigNumber = parts[9].trim();
                String status = parts[10].trim();
                String position = parts[11].trim();
                String supervisor = parts[12].trim();
                String basicSalary = parts[13].trim();
                String riceSubsidy = parts[14].trim();
                String phoneAllowance = parts[15].trim();
                String clothingAllowance = parts[16].trim();
                String hourlyRate = parts[18].trim();
                String leaveCredits = parts[21].trim();
                String approvedLeaves = parts[22].trim();
                String rejectedLeaves = parts[23].trim();

                // Set UI components with employee data
                txt_employee_number1.setText(employeeNumber);
                txt_last_name.setText(lastName);
                txt_firstname.setText(firstName);                
                txt_first_name.setText(firstName);
                txt_birthday.setText(birthday);
                txt_address.setText(address);
                txt_phone.setText(phoneNumber);
                txt_sss.setText(sssNumber);
                txt_philhealth.setText(philhealthNumber);
                txt_tin.setText(tinNumber);
                txt_pagibig.setText(pagibigNumber);
                txt_status.setText(status);
                txt_status1.setText(status);
                txt_position.setText(position);
                txt_position1.setText(position);
                txt_supervisor.setText(supervisor);
                txt_basic_salary.setText(basicSalary);
                txt_rice_subsidy3.setText(riceSubsidy);
                txt_phone_allowance3.setText(phoneAllowance);
                txt_clothing_allowance3.setText(clothingAllowance);
                txt_hourly_rate.setText(hourlyRate);
                txt_leaveCredits.setText(leaveCredits);
                txt_approvedLeaves.setText(approvedLeaves);
                txt_rejectedLeaves.setText(rejectedLeaves);
                
                found = true;
                break;
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(null, "Employee not found for Employee Number: " + employeeNumber);
        }
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error reading employee data. Please try again later.");
    }
}
    
    private void clock() {
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();
            date.setText(now.format(dateFormatter));
            time.setText(now.format(timeFormatter));
        });

        timer.setInitialDelay(0);
        timer.start();
    }
    
    public static double calculateSSSContribution(double totalSalary) {
                double sssContribution = 0;
                
                if (totalSalary <= 3250) {
                    sssContribution = 135;
                } else if (totalSalary <= 3750) {
                    sssContribution = 157.50;
                } else if (totalSalary <= 4250) {
                    sssContribution = 180;
                } else if (totalSalary <= 4750) {
                    sssContribution = 202.50;
                } else if (totalSalary <= 5250) {
                    sssContribution = 225;
                } else if (totalSalary <= 5750) {
                    sssContribution = 247.50;
                } else if (totalSalary <= 6250) {
                    sssContribution = 270;
                } else if (totalSalary <= 6750) {
                    sssContribution = 292.50;
                } else if (totalSalary <= 7250) {
                    sssContribution = 315;
                } else if (totalSalary <= 7750) {
                    sssContribution = 337.50;
                } else if (totalSalary <= 8250) {
                    sssContribution = 360;
                } else if (totalSalary <= 8750) {
                    sssContribution = 382.50;
                } else if (totalSalary <= 9250) {
                    sssContribution = 405;
                } else if (totalSalary <= 9750) {
                    sssContribution = 427.50;
                } else if (totalSalary <= 10250) {
                    sssContribution = 450;
                } else if (totalSalary <= 10750) {
                    sssContribution = 472.50;
                } else if (totalSalary <= 11250) {
                    sssContribution = 495;
                } else if (totalSalary <= 11750) {
                    sssContribution = 517.50;
                } else if (totalSalary <= 12250) {
                    sssContribution = 540;
                } else if (totalSalary <= 12750) {
                    sssContribution = 562.50;
                } else if (totalSalary <= 13250) {
                    sssContribution = 585;
                } else if (totalSalary <= 13750) {
                    sssContribution = 607.50;
                } else if (totalSalary <= 14250) {
                    sssContribution = 630;
                } else if (totalSalary <= 14750) {
                    sssContribution = 652.50;
                } else if (totalSalary <= 15250) {
                    sssContribution = 675;
                } else if (totalSalary <= 15750) {
                    sssContribution = 697.50;
                } else if (totalSalary <= 16250) {
                    sssContribution = 720;
                } else if (totalSalary <= 16750) {
                    sssContribution = 742.50;
                } else if (totalSalary <= 17250) {
                    sssContribution = 765;
                } else if (totalSalary <= 17750) {
                    sssContribution = 787.50;
                } else if (totalSalary <= 18250) {
                    sssContribution = 810;
                } else if (totalSalary <= 18750) {
                    sssContribution = 832.50;
                } else if (totalSalary <= 19250) {
                    sssContribution = 855;
                } else if (totalSalary <= 19750) {
                    sssContribution = 877.50;
                } else if (totalSalary <= 20250) {
                    sssContribution = 900;
                } else if (totalSalary <= 20750) {
                    sssContribution = 922.50;
                } else if (totalSalary <= 21250) {
                    sssContribution = 945;
                } else if (totalSalary <= 21750) {
                    sssContribution = 967.50;
                } else if (totalSalary <= 22250) {
                    sssContribution = 990;
                } else if (totalSalary <= 22750) {
                    sssContribution = 1012.50;
                } else if (totalSalary <= 23250) {
                    sssContribution = 1035;
                } else if (totalSalary <= 23750) {
                    sssContribution = 1057.50;
                } else if (totalSalary <= 24250) {
                    sssContribution = 1080;
                } else if (totalSalary <= 24750) {
                    sssContribution = 1102.50;
                } else {
                    sssContribution = 1125;
                }
            
                return sssContribution;
            }

            //Philhealth Method
            public static double calculatePhilHealthContribution(double totalSalary) {
                double premiumRate = 0.03; // 3% Premium Rate
        
                // Calculate monthly premium based on salary range
                double monthlyPremium;
                if (totalSalary <= 10000) {
                    monthlyPremium = 300;
                } else if (totalSalary <= 59999.99) {
                    monthlyPremium = Math.min(300 + (totalSalary - 10000) * premiumRate, 1800);
                } else {
                    monthlyPremium = 1800;
                }
        
                // Employee and employer share equally
                return monthlyPremium;
            }

            //Pagibig Method
            public static double calculatePagibigContribution(double totalSalary) {
                double employeeContributionRate = 0;
                double employerContributionRate = 0;
                double totalContributionRate = 0;
        
                if (totalSalary >= 1000 && totalSalary <= 1500) {
                    employeeContributionRate = 0.01;
                    employerContributionRate = 0.02;
                    totalContributionRate = employeeContributionRate + employerContributionRate;
                } else if (totalSalary > 1500) {
                    employeeContributionRate = 0.02;
                    employerContributionRate = 0.02;
                    totalContributionRate = employeeContributionRate + employerContributionRate;
                }
        
                // Calculate the contribution amount
                double totalContribution = Math.min(totalSalary * totalContributionRate, 100); // Maximum contribution is 100
        
                return totalContribution;
            }

            //Withholding Tax Method
            public static double calculateWithholdingTax(double salaryAfterTax) {
                double withholdingTax = 0;
        
                if (salaryAfterTax <= 20832) {
                    withholdingTax = 0;
                } else if (salaryAfterTax <= 33333) {
                    withholdingTax = (salaryAfterTax - 20832) * 0.20;
                } else if (salaryAfterTax <= 66667) {
                    withholdingTax = 2500 + (salaryAfterTax - 33333) * 0.25;
                } else if (salaryAfterTax <= 166667) {
                    withholdingTax = 10833 + (salaryAfterTax - 66667) * 0.30;
                } else if (salaryAfterTax <= 666667) {
                    withholdingTax = 40833.33 + (salaryAfterTax - 166667) * 0.32;
                } else {
                    withholdingTax = 200833.33 + (salaryAfterTax - 666667) * 0.35;
                }
        
                return withholdingTax;
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_change;
    private javax.swing.JButton button_edit_information;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_leave_form;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_view_salary;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel time;
    private javax.swing.JLabel txt_address;
    private javax.swing.JLabel txt_approvedLeaves;
    private javax.swing.JLabel txt_basic_salary;
    private javax.swing.JLabel txt_birthday;
    private javax.swing.JLabel txt_clothing_allowance3;
    private javax.swing.JLabel txt_employee_number1;
    private javax.swing.JLabel txt_first_name;
    private javax.swing.JLabel txt_firstname;
    private javax.swing.JLabel txt_hourly_rate;
    private javax.swing.JLabel txt_last_name;
    private javax.swing.JLabel txt_leaveCredits;
    private javax.swing.JLabel txt_pagibig;
    private javax.swing.JLabel txt_philhealth;
    private javax.swing.JLabel txt_phone;
    private javax.swing.JLabel txt_phone_allowance3;
    private javax.swing.JLabel txt_position;
    private javax.swing.JLabel txt_position1;
    private javax.swing.JLabel txt_position2;
    private javax.swing.JLabel txt_position3;
    private javax.swing.JLabel txt_position4;
    private javax.swing.JLabel txt_position5;
    private javax.swing.JLabel txt_rejectedLeaves;
    private javax.swing.JLabel txt_rice_subsidy3;
    private javax.swing.JLabel txt_sss;
    private javax.swing.JLabel txt_status;
    private javax.swing.JLabel txt_status1;
    private javax.swing.JLabel txt_supervisor;
    private javax.swing.JLabel txt_tin;
    // End of variables declaration//GEN-END:variables
}
