/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphemployee;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author set
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        loadCSVData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        private void loadCSVData() {
    // Path to your CSV file
    String csvFile = "/Users/set/Downloads/MotorPHEmployee/src/motorphemployee/data.csv"; //change depends on the file location of csv
    String line = "";
    String cvsSplitBy = ",";

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {

        // Read the header row to get column names
        if ((line = br.readLine()) != null) {
            String[] columns = line.split(cvsSplitBy);
            model.setColumnIdentifiers(columns);
            System.out.println("Columns: " + Arrays.toString(columns)); // Debugging
        }

        // Read data rows and add to table
        while ((line = br.readLine()) != null) {
            String[] data = line.split(cvsSplitBy);
            model.addRow(data);
            System.out.println("Data: " + Arrays.toString(data)); // Debugging
        }

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading data from CSV file: " + e.getMessage());
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_add = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtphonenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsss = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtphilhealth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpagibig = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtsupervisor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtclothing = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtbasicsalary = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtgrosssemi = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txthourlyrate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txttin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_add.setText("Add Employee");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_exit.setText("Exit");
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Birthday", "Address", "Phone Number", "SSS #", "Philhealth #", "TIN #", "Pag-ibig #", "Status", "Position", "Immediate Supervisor", "Basic Salary", "Rice Subsidy", "Phone Allowance", "Clothing Allowance", "Gross Semi-monthly Rate", "Hourly Rate"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Personal Information");

        jLabel2.setText("Employee Number");

        jLabel3.setText("Last Name");

        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });

        jLabel4.setText("First Name");

        jLabel5.setText("Birthday");

        txtbirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbirthdayActionPerformed(evt);
            }
        });

        jLabel6.setText("Phone Number");

        jLabel7.setText("Address");

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Tax Information");

        jLabel9.setText("SSS #:");

        jLabel10.setText("Philhealth #:");

        txtphilhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphilhealthActionPerformed(evt);
            }
        });

        jLabel11.setText("Pagibig #:");

        txtpagibig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagibigActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Employee Position:");

        jLabel13.setText("Status");

        jLabel14.setText("Position");

        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });

        jLabel15.setText("Immediate Supervisor");

        txtsupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupervisorActionPerformed(evt);
            }
        });

        jLabel16.setText("Benefits");

        jLabel17.setText("Rice Subsidy");

        jLabel18.setText("Phone Allowance");

        jLabel19.setText("Clothing Allowance");

        txtclothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclothingActionPerformed(evt);
            }
        });

        jLabel20.setText("Salary Information");

        jLabel21.setText("Basic Salary");

        jLabel22.setText("Gross Semi-monthly Rate");

        txtgrosssemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrosssemiActionPerformed(evt);
            }
        });

        jLabel23.setText("Hourly Rate");

        jLabel24.setText("TIN #:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(txtlastname)
                                .addComponent(txtfirstname)
                                .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                                .addComponent(txtphonenumber)
                                .addComponent(txtbirthday)
                                .addComponent(txtid)))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(txtsss)
                            .addComponent(jLabel10)
                            .addComponent(txtphilhealth)
                            .addComponent(jLabel11)
                            .addComponent(txtpagibig)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(txtstatus)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(txtposition)
                            .addComponent(txtsupervisor)
                            .addComponent(jLabel24)
                            .addComponent(txttin, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(txtrice)
                            .addComponent(jLabel18)
                            .addComponent(txtphone)
                            .addComponent(jLabel19)
                            .addComponent(txtclothing)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(txtbasicsalary)
                            .addComponent(jLabel22)
                            .addComponent(txtgrosssemi)
                            .addComponent(jLabel23)
                            .addComponent(txthourlyrate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(button_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_exit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtgrosssemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthourlyrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_update)
                            .addComponent(button_delete))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphilhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpagibig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtclothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtbasicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
        if(txtid.getText().equals("") || txtaddress.getText().equals("") || txtbasicsalary.getText().equals("") || txtbirthday.getText().equals("") || txtclothing.getText().equals("") || txtfirstname.getText().equals("") || txtgrosssemi.getText().equals("") || txthourlyrate.getText().equals("") || txtlastname.getText().equals("") || txtpagibig.getText().equals("") || txtphilhealth.getText().equals("") || txtphone.getText().equals("") || txtphonenumber.getText().equals("") || txtposition.getText().equals("") || txtrice.getText().equals("") || txtsss.getText().equals("") || txtstatus.getText().equals("") || txtsupervisor.getText().equals("") || txttin.getText().equals("")) {
    // Handle the case where at least one field is empty
    JOptionPane.showMessageDialog(this, "Please Enter All Data");
} else {
            String data[] = {
    txtid.getText(),               // Employee #
    txtaddress.getText(),          // Last Name
    txtbasicsalary.getText(),      // First Name
    txtbirthday.getText(),         // Birthday
    txtclothing.getText(),         // Address
    txtfirstname.getText(),        // Phone Number
    txtsss.getText(),              // SSS #
    txtphilhealth.getText(),       // Philhealth #
    txttin.getText(),              // TIN #
    txtpagibig.getText(),          // Pag-ibig #
    txtstatus.getText(),           // Status
    txtposition.getText(),         // Position
    txtsupervisor.getText(),       // Immediate Supervisor
    txtbasicsalary.getText(),      // Basic Salary
    txtrice.getText(),             // Rice Subsidy
    txtsss.getText(),              // Phone Allowance (assuming this was intended)
    txtclothing.getText(),         // Clothing Allowance
    txtgrosssemi.getText(),        // Gross Semi-monthly Rate
    txthourlyrate.getText()        // Hourly Rate
};
                    DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(data);

    // Proceed with your logic, as all fields are filled
}

    }//GEN-LAST:event_button_addActionPerformed

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:                                    
    // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Check if exactly one row is selected
    if (jTable1.getSelectedRowCount() == 1) {
        // Retrieve the updated values from the text fields
        String id = txtid.getText();
        String lastName = txtlastname.getText();
        String firstName = txtfirstname.getText();
        String birthday = txtbirthday.getText();
        String address = txtaddress.getText();
        String phoneNumber = txtphonenumber.getText();
        String sss = txtsss.getText();
        String philhealth = txtphilhealth.getText();
        String tin = txttin.getText();
        String pagibig = txtpagibig.getText();
        String status = txtstatus.getText();
        String position = txtposition.getText();
        String supervisor = txtsupervisor.getText();
        String basicSalary = txtbasicsalary.getText();
        String riceSubsidy = txtrice.getText();
        String phoneAllowance = txtphone.getText();
        String clothingAllowance = txtclothing.getText();
        String grossSemiMonthlyRate = txtgrosssemi.getText();
        String hourlyRate = txthourlyrate.getText();
        
        // Set the updated values in the selected row
        tblModel.setValueAt(id, jTable1.getSelectedRow(), 0);
        tblModel.setValueAt(lastName, jTable1.getSelectedRow(), 1);
        tblModel.setValueAt(firstName, jTable1.getSelectedRow(), 2);
        tblModel.setValueAt(birthday, jTable1.getSelectedRow(), 3);
        tblModel.setValueAt(address, jTable1.getSelectedRow(), 4);
        tblModel.setValueAt(phoneNumber, jTable1.getSelectedRow(), 5);
        tblModel.setValueAt(sss, jTable1.getSelectedRow(), 6);
        tblModel.setValueAt(philhealth, jTable1.getSelectedRow(), 7);
        tblModel.setValueAt(tin, jTable1.getSelectedRow(), 8);
        tblModel.setValueAt(pagibig, jTable1.getSelectedRow(), 9);
        tblModel.setValueAt(status, jTable1.getSelectedRow(), 10);
        tblModel.setValueAt(position, jTable1.getSelectedRow(), 11);
        tblModel.setValueAt(supervisor, jTable1.getSelectedRow(), 12);
        tblModel.setValueAt(basicSalary, jTable1.getSelectedRow(), 13);
        tblModel.setValueAt(riceSubsidy, jTable1.getSelectedRow(), 14);
        tblModel.setValueAt(phoneAllowance, jTable1.getSelectedRow(), 15);
        tblModel.setValueAt(clothingAllowance, jTable1.getSelectedRow(), 16);
        tblModel.setValueAt(grossSemiMonthlyRate, jTable1.getSelectedRow(), 17);
        tblModel.setValueAt(hourlyRate, jTable1.getSelectedRow(), 18);
        
        //update message display if successful
        
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
        // Display update message or perform any other necessary actions
    } else {
        if(jTable1.getRowCount () ==0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else{
            JOptionPane.showMessageDialog(this, "Please select Single Row For Update");
        }
    }
    }//GEN-LAST:event_button_updateActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtbirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirthdayActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphilhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphilhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphilhealthActionPerformed

    private void txtpagibigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagibigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagibigActionPerformed

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed

    private void txtsupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupervisorActionPerformed

    private void txtclothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclothingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclothingActionPerformed

    private void txtgrosssemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrosssemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrosssemiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            
// Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalary = tblModel.getValueAt(selectedRowIndex, 13).toString();;
        String riceSubsidy = tblModel.getValueAt(selectedRowIndex, 14).toString();;
        String phoneAllowance = tblModel.getValueAt(selectedRowIndex, 15).toString();;
        String clothingAllowance = tblModel.getValueAt(selectedRowIndex, 16).toString();;
        String grossSemiMonthlyRate = tblModel.getValueAt(selectedRowIndex, 17).toString();;
        String hourlyRate = tblModel.getValueAt(selectedRowIndex, 18).toString();;
        
        // Set retrieved values to text fields
        
        txtid.setText(id);
        txtlastname.setText(lastName);
        txtfirstname.setText(firstName);
        txtbirthday.setText(birthday);
        txtaddress.setText(address);
        txtphonenumber.setText(phoneNumber);
        txtsss.setText(sss);
        txtphilhealth.setText(philhealth);
        txttin.setText(tin);
        txtpagibig.setText(pagibig);
        txtstatus.setText(status);
        txtposition.setText(position);
        txtsupervisor.setText(supervisor);
        txtbasicsalary.setText(basicSalary);
        txtrice.setText(riceSubsidy);
        txtphone.setText(phoneAllowance);
        txtclothing.setText(clothingAllowance);
        txtgrosssemi.setText(grossSemiMonthlyRate);
        txthourlyrate.setText(hourlyRate);
      
}
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        // get jtable model
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        
        //delete row
        if (jTable1.getSelectedRowCount()==1){
            //if single row selected then delete
            tblModel.removeRow(jTable1.getSelectedRow());
        } else {
            if(jTable1.getRowCount()==0){
                //if the table is empty (no data) display message
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }  else {
                // if table is not empty but row is not selected or multiple is selected
                 JOptionPane.showMessageDialog(this, "Please select single row for delete.");  
            }}
   
    }//GEN-LAST:event_button_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtbasicsalary;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtclothing;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgrosssemi;
    private javax.swing.JTextField txthourlyrate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtpagibig;
    private javax.swing.JTextField txtphilhealth;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtrice;
    private javax.swing.JTextField txtsss;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtsupervisor;
    private javax.swing.JTextField txttin;
    // End of variables declaration//GEN-END:variables
}
