/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphemployee;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author set
 */
public class MainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form MainMenu
     * 
     */
    
    
    
    public MainMenu() {
        initComponents();
        loadCSVData();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private String csvFile = "src/motorphemployee/data.csv"; //Change depends on the file location of csv (optional)

        private void loadCSVData() { // CSV File Reader
    // Path to CSV File
    String line = "";
    String cvsSplitBy = ",";

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {

        // Read the header row to get column names
        if ((line = br.readLine()) != null) {
            String[] columns = line.split(cvsSplitBy);
            model.setColumnIdentifiers(columns);

            // Adjust column widths to hide specific columns
            int[] hiddenColumns = {3, 4, 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23}; // Specify indices of columns to hide
            for (int columnIndex : hiddenColumns) {
                jTable1.getColumnModel().getColumn(columnIndex).setMinWidth(0);
                jTable1.getColumnModel().getColumn(columnIndex).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(columnIndex).setPreferredWidth(0);
            }
        }

        // Read data rows and add to table
        while ((line = br.readLine()) != null) {
            String[] data = line.split(cvsSplitBy);
            model.addRow(data);
        }

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading data from CSV file: " + e.getMessage());
    }
}

        
        private void saveCSVData() { //CSV File Editor thru Save Button
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(csvFile))) {

            // Write the header row
            for (int i = 0; i < model.getColumnCount(); i++) {
                bw.write(model.getColumnName(i));
                if (i < model.getColumnCount() - 1) {
                    bw.write(",");
                }
            }
            bw.newLine();

            // Write data rows
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    bw.write(model.getValueAt(i, j).toString());
                    if (j < model.getColumnCount() - 1) {
                        bw.write(",");
                    }
                }
                bw.newLine();
            }
                
               JOptionPane.showMessageDialog(this, "Saved successfully!");

         } catch (IOException e) {
             e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error saving data to CSV file: " + e.getMessage());
            }
}
        
      
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_cleartext = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtphonenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtsupervisor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txttin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsss = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtphilhealth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpagibig = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtclothing = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtbasicsalary = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtgrosssemi = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txthourlyrate = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        leave_management = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_calculatesalary = new javax.swing.JButton();
        button_information = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Birthday", "Address", "Phone Number", "SSS #", "Philhealth #", "TIN #", "Pag-ibig #", "Status", "Position", "Immediate Supervisor", "Basic Salary", "Rice Subsidy", "Phone Allowance", "Clothing Allowance", "Gross Semi-monthly Rate", "Hourly Rate"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionBackground(new java.awt.Color(248, 140, 140));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setMinWidth(0);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(10).setMinWidth(0);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(11).setMinWidth(0);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(11).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(12).setMinWidth(0);
            jTable1.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(12).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(13).setMinWidth(0);
            jTable1.getColumnModel().getColumn(13).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(13).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(14).setMinWidth(0);
            jTable1.getColumnModel().getColumn(14).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(14).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(15).setMinWidth(0);
            jTable1.getColumnModel().getColumn(15).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(15).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(16).setMinWidth(0);
            jTable1.getColumnModel().getColumn(16).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(16).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(17).setMinWidth(0);
            jTable1.getColumnModel().getColumn(17).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(17).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(18).setMinWidth(0);
            jTable1.getColumnModel().getColumn(18).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(18).setMaxWidth(0);
        }

        button_cleartext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clean.png"))); // NOI18N
        button_cleartext.setText("Clear Text");
        button_cleartext.setToolTipText("");
        button_cleartext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cleartextActionPerformed(evt);
            }
        });

        button_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel26.setText("MotorPH Employee Management Payroll System");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MotorPH logo.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Personal Information");

        jLabel2.setText("Employee Number");

        jLabel3.setText("Last Name");

        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });

        jLabel4.setText("First Name");

        jLabel5.setText("Birthday");

        txtbirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbirthdayActionPerformed(evt);
            }
        });

        jLabel6.setText("Phone Number");

        jLabel7.setText("Address");

        txtaddress.setColumns(20);
        txtaddress.setLineWrap(true);
        txtaddress.setRows(5);
        jScrollPane2.setViewportView(txtaddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtphonenumber)
                            .addComponent(txtbirthday)
                            .addComponent(txtfirstname)
                            .addComponent(txtlastname)
                            .addComponent(txtid)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setText("Immediate Supervisor");

        txtsupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupervisorActionPerformed(evt);
            }
        });

        jLabel24.setText("TIN #:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Tax Information");

        jLabel9.setText("SSS #:");

        jLabel10.setText("Philhealth #:");

        txtphilhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphilhealthActionPerformed(evt);
            }
        });

        jLabel11.setText("Pagibig #:");

        txtpagibig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagibigActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Employee Position:");

        jLabel13.setText("Status");

        jLabel14.setText("Position");

        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtsupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtposition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtstatus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpagibig, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtphilhealth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsss, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtphilhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpagibig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Benefits:");

        jLabel17.setText("Rice Subsidy");

        txtrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtriceActionPerformed(evt);
            }
        });

        jLabel18.setText("Phone Allowance");

        jLabel19.setText("Clothing Allowance");

        txtclothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclothingActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel20.setText("Salary Information:");

        jLabel21.setText("Basic Salary");

        jLabel22.setText("Gross Semi-monthly Rate");

        txtgrosssemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrosssemiActionPerformed(evt);
            }
        });

        jLabel23.setText("Hourly Rate");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txtrice, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtphone)
                    .addComponent(txtclothing)
                    .addComponent(txtbasicsalary)
                    .addComponent(txtgrosssemi)
                    .addComponent(txthourlyrate))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(txtgrosssemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtclothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbasicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthourlyrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-button.png"))); // NOI18N
        refresh.setText("Refresh");
        refresh.setToolTipText("");
        refresh.setRequestFocusEnabled(false);
        refresh.setVerifyInputWhenFocusTarget(false);
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(244, 69, 69));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        add.setText("Add Employee");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        leave_management.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/form.png"))); // NOI18N
        leave_management.setText("Leave Management");
        leave_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_managementActionPerformed(evt);
            }
        });

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        button_exit.setText("Exit");
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leave_management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(leave_management, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(logOut)
                .addGap(18, 18, 18)
                .addComponent(button_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_delete.setBackground(new java.awt.Color(204, 0, 0));
        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bin.png"))); // NOI18N
        button_delete.setText("Delete User");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        button_update.setText("Update Details");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_calculatesalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/accounting.png"))); // NOI18N
        button_calculatesalary.setText("Calculate Salary");
        button_calculatesalary.setToolTipText("");
        button_calculatesalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_calculatesalaryActionPerformed(evt);
            }
        });

        button_information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/information.png"))); // NOI18N
        button_information.setText("View Information");
        button_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_informationActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel25.setText("Employee's Information Table");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel27.setText("Great to have you here, ");

        jLabel28.setText("Work hard, stay focused, and never give up. Your dedication will pay off.");
        jLabel28.setEnabled(false);

        txt_firstname.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txt_firstname.setText("HR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(0, 0, 0)
                        .addComponent(txt_firstname))
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_firstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        time.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        time.setText("Time");
        time.setToolTipText("");

        date.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        date.setText("Date");
        date.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date)
                            .addComponent(time)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_calculatesalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 619, Short.MAX_VALUE)
                                .addComponent(button_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_cleartext))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date))
                            .addComponent(jLabel26))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_save)
                    .addComponent(button_cleartext)
                    .addComponent(refresh)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_information)
                        .addGap(18, 18, 18)
                        .addComponent(button_calculatesalary)
                        .addGap(18, 18, 18)
                        .addComponent(button_update)
                        .addGap(18, 18, 18)
                        .addComponent(button_delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:                                    
    // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
if (jTable1.getSelectedRowCount() == 1) {
    try {
        // Retrieve the updated values from the text fields
        String id = txtid.getText();
        String lastName = txtlastname.getText();
        String firstName = txtfirstname.getText();
        String birthday = txtbirthday.getText();
        String address = txtaddress.getText();
        String phoneNumber = txtphonenumber.getText();
        String sss = txtsss.getText();
        String philhealth = txtphilhealth.getText();
        String tin = txttin.getText();
        String pagibig = txtpagibig.getText();
        String status = txtstatus.getText();
        String position = txtposition.getText();
        String supervisor = txtsupervisor.getText();
        String basicSalaryStr = txtbasicsalary.getText();
        String riceSubsidyStr = txtrice.getText();
        String phoneAllowanceStr = txtphone.getText();
        String clothingAllowanceStr = txtclothing.getText();
        String grossSemiMonthlyRateStr = txtgrosssemi.getText();
        String hourlyRateStr = txthourlyrate.getText();

        // Validate and parse numeric fields
        int idNumber = Integer.parseInt(id);
        double basicSalary = Double.parseDouble(basicSalaryStr);
        double riceSubsidy = Double.parseDouble(riceSubsidyStr);
        double phoneAllowance = Double.parseDouble(phoneAllowanceStr);
        double clothingAllowance = Double.parseDouble(clothingAllowanceStr);
        double grossSemiMonthlyRate = Double.parseDouble(grossSemiMonthlyRateStr);
        double hourlyRate = Double.parseDouble(hourlyRateStr);

        // Check if the employee ID is unique
        boolean isUnique = true;
        for (int i = 0; i < tblModel.getRowCount(); i++) {
            if (i != jTable1.getSelectedRow() && id.equals(tblModel.getValueAt(i, 0).toString())) {
                isUnique = false;
                break;
            }
        }

        if (!isUnique) {
            JOptionPane.showMessageDialog(this, "Employee ID must be unique.");
            return;
        }

        // Set the updated values in the selected row
        tblModel.setValueAt(id, jTable1.getSelectedRow(), 0);
        tblModel.setValueAt(lastName, jTable1.getSelectedRow(), 1);
        tblModel.setValueAt(firstName, jTable1.getSelectedRow(), 2);
        tblModel.setValueAt(birthday, jTable1.getSelectedRow(), 3);
        tblModel.setValueAt(address, jTable1.getSelectedRow(), 4);
        tblModel.setValueAt(phoneNumber, jTable1.getSelectedRow(), 5);
        tblModel.setValueAt(sss, jTable1.getSelectedRow(), 6);
        tblModel.setValueAt(philhealth, jTable1.getSelectedRow(), 7);
        tblModel.setValueAt(tin, jTable1.getSelectedRow(), 8);
        tblModel.setValueAt(pagibig, jTable1.getSelectedRow(), 9);
        tblModel.setValueAt(status, jTable1.getSelectedRow(), 10);
        tblModel.setValueAt(position, jTable1.getSelectedRow(), 11);
        tblModel.setValueAt(supervisor, jTable1.getSelectedRow(), 12);
        tblModel.setValueAt(basicSalaryStr, jTable1.getSelectedRow(), 13);
        tblModel.setValueAt(riceSubsidyStr, jTable1.getSelectedRow(), 14);
        tblModel.setValueAt(phoneAllowanceStr, jTable1.getSelectedRow(), 15);
        tblModel.setValueAt(clothingAllowanceStr, jTable1.getSelectedRow(), 16);
        tblModel.setValueAt(grossSemiMonthlyRateStr, jTable1.getSelectedRow(), 17);
        tblModel.setValueAt(hourlyRateStr, jTable1.getSelectedRow(), 18);

        // Update message display if successful
        JOptionPane.showMessageDialog(this, "Update Successfully");

        // Display update message or perform any other necessary actions
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please ensure all numeric fields (ID, Salary, Allowances, etc.) are valid numbers.");
    }
} else {
    if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Table is Empty");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a Single Row For Update");
    }
}
    }//GEN-LAST:event_button_updateActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtbirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirthdayActionPerformed

    private void txtphilhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphilhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphilhealthActionPerformed

    private void txtpagibigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagibigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagibigActionPerformed

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed

    private void txtsupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupervisorActionPerformed

    private void txtclothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclothingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclothingActionPerformed

    private void txtgrosssemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrosssemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrosssemiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            
    // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalary = tblModel.getValueAt(selectedRowIndex, 13).toString();;
        String riceSubsidy = tblModel.getValueAt(selectedRowIndex, 14).toString();;
        String phoneAllowance = tblModel.getValueAt(selectedRowIndex, 15).toString();;
        String clothingAllowance = tblModel.getValueAt(selectedRowIndex, 16).toString();;
        String grossSemiMonthlyRate = tblModel.getValueAt(selectedRowIndex, 17).toString();;
        String hourlyRate = tblModel.getValueAt(selectedRowIndex, 18).toString();;
        
        // Set retrieved values to text fields
        
        txtid.setText(id);
        txtlastname.setText(lastName);
        txtfirstname.setText(firstName);
        txtbirthday.setText(birthday);
        txtaddress.setText(address);
        txtphonenumber.setText(phoneNumber);
        txtsss.setText(sss);
        txtphilhealth.setText(philhealth);
        txttin.setText(tin);
        txtpagibig.setText(pagibig);
        txtstatus.setText(status);
        txtposition.setText(position);
        txtsupervisor.setText(supervisor);
        txtbasicsalary.setText(basicSalary);
        txtrice.setText(riceSubsidy);
        txtphone.setText(phoneAllowance);
        txtclothing.setText(clothingAllowance);
        txtgrosssemi.setText(grossSemiMonthlyRate);
        txthourlyrate.setText(hourlyRate);   
}
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:                                              
    // Get the selected row count
    int selectedRowCount = jTable1.getSelectedRowCount();
    
    // Check if exactly one row is selected
    if (selectedRowCount == 1) {
        // Prompt the user for confirmation
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected row?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        
        // Check user's response
        if (option == JOptionPane.YES_OPTION) {
            // If user confirms deletion, delete the selected row
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.removeRow(jTable1.getSelectedRow());
        }
    } else {
        if (jTable1.getRowCount() == 0) {
            // If the table is empty, display a message
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            // If multiple rows are selected or no row is selected, display a message
            JOptionPane.showMessageDialog(this, "Please select a single row for deletion.");
        }
    }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_calculatesalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_calculatesalaryActionPerformed
        // TODO add your handling code here:
    // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalaryStr = tblModel.getValueAt(selectedRowIndex, 13).toString();
        String riceSubsidyStr = tblModel.getValueAt(selectedRowIndex, 14).toString();
        String phoneAllowanceStr = tblModel.getValueAt(selectedRowIndex, 15).toString();
        String clothingAllowanceStr = tblModel.getValueAt(selectedRowIndex, 16).toString();
        String grossSemiMonthlyRateStr = tblModel.getValueAt(selectedRowIndex, 17).toString();
        String hourlyRateStr = tblModel.getValueAt(selectedRowIndex, 18).toString();
        
        // Convert string to double
        double hourlyRate = Double.parseDouble(hourlyRateStr);

        // Array of months
        String[] months = {
            "January", "February", "March", "April",
            "May", "June", "July", "August",
            "September", "October", "November", "December"
        };

        // Array of number of working days corresponding to each month
        int[] workingDays = {
            23, 21, 21, 22,
            23, 20, 23, 22,
            21, 23, 21, 22
        }; //Reference: https://hr.uiowa.edu/pay/payroll-services/payroll-calendars/working-day-payroll-calendar-2024

        // Let the user choose the month
        String selectedMonth = (String) JOptionPane.showInputDialog(
            this,
            "Choose a month:",
            "Month Selection",
            JOptionPane.PLAIN_MESSAGE,
            null,
            months,
            null
        );

        if (selectedMonth != null) { // If user selects a month
            // Retrieve the number of working days for the selected month
            int index = Arrays.asList(months).indexOf(selectedMonth);
            int workedDays = workingDays[index];

            // Calculate total salary
            double totalSalary = workedDays * hourlyRate * 8; //Assuming working 8 hours a day

            // Call SSS, PhilHealth, Pagibig methods
            double sssContribution = calculateSSSContribution(totalSalary);
            double philhealthContribution = calculatePhilHealthContribution(totalSalary);
            double pagibigContribution = calculatePagibigContribution(totalSalary);

            // Calculate total deductions without WithHolding Tax
            double grossDeductions = sssContribution + philhealthContribution + pagibigContribution;

            // Calculate Salary After Tax
            double salaryAfterTax = totalSalary - grossDeductions;

            // Call Withholding Tax methods
            double withholdingTax = calculateWithholdingTax(salaryAfterTax);

            // Calculate total deductions
            double totalDeductions = grossDeductions + withholdingTax;

            // Calculate Net Pay
            double netPay = salaryAfterTax - withholdingTax;

            // Display salary and deductions in a dialog
            String message = "Employee Information:\n";
            message += "ID: " + id + "\n";
            message += "Name: " + firstName + " " + lastName + "\n";
            message += "Birthday: " + birthday + "\n";
            message += "Address: " + address + "\n";
            message += "Phone Number: " + phoneNumber + "\n";
            message += "SSS: " + sss + "\n";
            message += "PhilHealth: " + philhealth + "\n";
            message += "TIN: " + tin + "\n";
            message += "Pagibig: " + pagibig + "\n";
            message += "Status: " + status + "\n";
            message += "Position: " + position + "\n";
            message += "Supervisor: " + supervisor + "\n";
            message += "Basic Salary: " + basicSalaryStr + "\n";
            message += "Rice Subsidy: " + riceSubsidyStr + "\n";
            message += "Phone Allowance: " + phoneAllowanceStr + "\n";
            message += "Clothing Allowance: " + clothingAllowanceStr + "\n";
            message += "Gross Semi-Monthly Rate: " + grossSemiMonthlyRateStr + "\n";
            message += "Hourly Rate: " + hourlyRateStr + "\n\n";
            message += "Salary Details for " + selectedMonth + ":\n";
            message += "Worked Days: " + workedDays + "\n";
            message += "Gross Salary: PHP " + String.format("%.2f", totalSalary) + "\n";
            message += "SSS Contribution: PHP " + String.format("%.2f", sssContribution) + "\n";
            message += "PhilHealth Contribution: PHP " + String.format("%.2f", philhealthContribution) + "\n";
            message += "Pagibig Contribution: PHP " + String.format("%.2f", pagibigContribution) + "\n";
            message += "Withholding Tax: PHP " + String.format("%.2f", withholdingTax) + "\n";
            message += "Total Deductions: PHP " + String.format("%.2f", totalDeductions) + "\n";
            message += "Net Pay: PHP " + String.format("%.2f", netPay) + "\n";

            JOptionPane.showMessageDialog(this, message);
        } else {
        }  
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to calculate salary.");
    }   
    }//GEN-LAST:event_button_calculatesalaryActionPerformed

    private void button_cleartextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cleartextActionPerformed
        // TODO add your handling code here:
        
    //Clear text
    txtid.setText("");
    txtaddress.setText("");
    txtbasicsalary.setText("");
    txtbirthday.setText("");
    txtclothing.setText("");
    txtfirstname.setText("");
    txtgrosssemi.setText("");
    txthourlyrate.setText("");
    txtlastname.setText("");
    txtpagibig.setText("");
    txtphilhealth.setText("");
    txtphone.setText("");
    txtphonenumber.setText("");
    txtposition.setText("");
    txtrice.setText("");
    txtsss.setText("");
    txtstatus.setText("");
    txtsupervisor.setText("");
    txttin.setText("");
    }//GEN-LAST:event_button_cleartextActionPerformed

    private void txtriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtriceActionPerformed

    private void button_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_informationActionPerformed
        // TODO add your handling code here:
        // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalary = tblModel.getValueAt(selectedRowIndex, 13).toString();;
        String riceSubsidy = tblModel.getValueAt(selectedRowIndex, 14).toString();;
        String phoneAllowance = tblModel.getValueAt(selectedRowIndex, 15).toString();;
        String clothingAllowance = tblModel.getValueAt(selectedRowIndex, 16).toString();;
        String grossSemiMonthlyRate = tblModel.getValueAt(selectedRowIndex, 17).toString();;
        String hourlyRate = tblModel.getValueAt(selectedRowIndex, 18).toString();;
        
        // Display the information in a dialog
        String message = "Employee ID: " + id + "\n";
        message += "Last Name: " + lastName + "\n";
        message += "First Name: " + firstName + "\n";
        message += "Birthday: " + birthday + "\n";
        message += "Address: " + address + "\n";
        message += "Phone Number: " + phoneNumber + "\n";
        message += "SSS: " + sss + "\n";
        message += "Philhealth: " + philhealth + "\n";
        message += "TIN: " + tin + "\n";
        message += "Pag-ibig: " + pagibig + "\n";
        message += "Status: " + status + "\n";
        message += "Position: " + position + "\n";
        message += "Supervisor: " + supervisor + "\n";
        message += "Basic Salary: " + basicSalary + "\n";
        message += "Rice Subsidy: " + riceSubsidy + "\n";
        message += "Phone Allowance: " + phoneAllowance + "\n";
        message += "Clothing Allowance: " + clothingAllowance + "\n";
        message += "Gross Semi-monthly Rate: " + grossSemiMonthlyRate + "\n";
        message += "Hourly Rate: " + hourlyRate + "\n";
        
        JOptionPane.showMessageDialog(this, message);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to view information.");
    }
    }//GEN-LAST:event_button_informationActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        saveCSVData();
    }//GEN-LAST:event_button_saveActionPerformed

    private void leave_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_managementActionPerformed
    // TODO add your handling code here:
    LeaveManagement leaveManagement = new LeaveManagement();
    
    // Make the LeaveManagement window visible
    leaveManagement.setVisible(true);
    
    }//GEN-LAST:event_leave_managementActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);
    
    if (option == JOptionPane.YES_OPTION) {
        this.dispose();
        
        // Open the login window
        Login loginWindow = new Login();
        loginWindow.setVisible(true);
    }
    }//GEN-LAST:event_logOutActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Form form = new Form();
        form.setVisible(true);

    }//GEN-LAST:event_addActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        tblModel.setRowCount(0);
        loadCSVData();
    }//GEN-LAST:event_refreshActionPerformed
    // Will transfer this methods on other file soon
    //SSS Method
            public static double calculateSSSContribution(double totalSalary) {
                double sssContribution = 0;
                
                if (totalSalary <= 3250) {
                    sssContribution = 135;
                } else if (totalSalary <= 3750) {
                    sssContribution = 157.50;
                } else if (totalSalary <= 4250) {
                    sssContribution = 180;
                } else if (totalSalary <= 4750) {
                    sssContribution = 202.50;
                } else if (totalSalary <= 5250) {
                    sssContribution = 225;
                } else if (totalSalary <= 5750) {
                    sssContribution = 247.50;
                } else if (totalSalary <= 6250) {
                    sssContribution = 270;
                } else if (totalSalary <= 6750) {
                    sssContribution = 292.50;
                } else if (totalSalary <= 7250) {
                    sssContribution = 315;
                } else if (totalSalary <= 7750) {
                    sssContribution = 337.50;
                } else if (totalSalary <= 8250) {
                    sssContribution = 360;
                } else if (totalSalary <= 8750) {
                    sssContribution = 382.50;
                } else if (totalSalary <= 9250) {
                    sssContribution = 405;
                } else if (totalSalary <= 9750) {
                    sssContribution = 427.50;
                } else if (totalSalary <= 10250) {
                    sssContribution = 450;
                } else if (totalSalary <= 10750) {
                    sssContribution = 472.50;
                } else if (totalSalary <= 11250) {
                    sssContribution = 495;
                } else if (totalSalary <= 11750) {
                    sssContribution = 517.50;
                } else if (totalSalary <= 12250) {
                    sssContribution = 540;
                } else if (totalSalary <= 12750) {
                    sssContribution = 562.50;
                } else if (totalSalary <= 13250) {
                    sssContribution = 585;
                } else if (totalSalary <= 13750) {
                    sssContribution = 607.50;
                } else if (totalSalary <= 14250) {
                    sssContribution = 630;
                } else if (totalSalary <= 14750) {
                    sssContribution = 652.50;
                } else if (totalSalary <= 15250) {
                    sssContribution = 675;
                } else if (totalSalary <= 15750) {
                    sssContribution = 697.50;
                } else if (totalSalary <= 16250) {
                    sssContribution = 720;
                } else if (totalSalary <= 16750) {
                    sssContribution = 742.50;
                } else if (totalSalary <= 17250) {
                    sssContribution = 765;
                } else if (totalSalary <= 17750) {
                    sssContribution = 787.50;
                } else if (totalSalary <= 18250) {
                    sssContribution = 810;
                } else if (totalSalary <= 18750) {
                    sssContribution = 832.50;
                } else if (totalSalary <= 19250) {
                    sssContribution = 855;
                } else if (totalSalary <= 19750) {
                    sssContribution = 877.50;
                } else if (totalSalary <= 20250) {
                    sssContribution = 900;
                } else if (totalSalary <= 20750) {
                    sssContribution = 922.50;
                } else if (totalSalary <= 21250) {
                    sssContribution = 945;
                } else if (totalSalary <= 21750) {
                    sssContribution = 967.50;
                } else if (totalSalary <= 22250) {
                    sssContribution = 990;
                } else if (totalSalary <= 22750) {
                    sssContribution = 1012.50;
                } else if (totalSalary <= 23250) {
                    sssContribution = 1035;
                } else if (totalSalary <= 23750) {
                    sssContribution = 1057.50;
                } else if (totalSalary <= 24250) {
                    sssContribution = 1080;
                } else if (totalSalary <= 24750) {
                    sssContribution = 1102.50;
                } else {
                    sssContribution = 1125;
                }
            
                return sssContribution;
            }

            //Philhealth Method
            public static double calculatePhilHealthContribution(double totalSalary) {
                double premiumRate = 0.03; // 3% Premium Rate
        
                // Calculate monthly premium based on salary range
                double monthlyPremium;
                if (totalSalary <= 10000) {
                    monthlyPremium = 300;
                } else if (totalSalary <= 59999.99) {
                    monthlyPremium = Math.min(300 + (totalSalary - 10000) * premiumRate, 1800);
                } else {
                    monthlyPremium = 1800;
                }
        
                // Employee and employer share equally
                return monthlyPremium;
            }

            //Pagibig Method
            public static double calculatePagibigContribution(double totalSalary) {
                double employeeContributionRate = 0;
                double employerContributionRate = 0;
                double totalContributionRate = 0;
        
                if (totalSalary >= 1000 && totalSalary <= 1500) {
                    employeeContributionRate = 0.01;
                    employerContributionRate = 0.02;
                    totalContributionRate = employeeContributionRate + employerContributionRate;
                } else if (totalSalary > 1500) {
                    employeeContributionRate = 0.02;
                    employerContributionRate = 0.02;
                    totalContributionRate = employeeContributionRate + employerContributionRate;
                }
        
                // Calculate the contribution amount
                double totalContribution = Math.min(totalSalary * totalContributionRate, 100); // Maximum contribution is 100
        
                return totalContribution;
            }

            //Withholding Tax Method
            public static double calculateWithholdingTax(double salaryAfterTax) {
                double withholdingTax = 0;
        
                if (salaryAfterTax <= 20832) {
                    withholdingTax = 0;
                } else if (salaryAfterTax <= 33333) {
                    withholdingTax = (salaryAfterTax - 20832) * 0.20;
                } else if (salaryAfterTax <= 66667) {
                    withholdingTax = 2500 + (salaryAfterTax - 33333) * 0.25;
                } else if (salaryAfterTax <= 166667) {
                    withholdingTax = 10833 + (salaryAfterTax - 66667) * 0.30;
                } else if (salaryAfterTax <= 666667) {
                    withholdingTax = 40833.33 + (salaryAfterTax - 166667) * 0.32;
                } else {
                    withholdingTax = 200833.33 + (salaryAfterTax - 666667) * 0.35;
                }
        
                return withholdingTax;
            }
            
            private void clock() {
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();
            date.setText(now.format(dateFormatter));
            time.setText(now.format(timeFormatter));
        });

        timer.setInitialDelay(0);
        timer.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton button_calculatesalary;
    private javax.swing.JButton button_cleartext;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_information;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton leave_management;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel logo;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel time;
    private javax.swing.JLabel txt_firstname;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtbasicsalary;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtclothing;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgrosssemi;
    private javax.swing.JTextField txthourlyrate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtpagibig;
    private javax.swing.JTextField txtphilhealth;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtrice;
    private javax.swing.JTextField txtsss;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtsupervisor;
    private javax.swing.JTextField txttin;
    // End of variables declaration//GEN-END:variables
}
