/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphemployee;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author set
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    public MainMenu() {
        initComponents();
        loadCSVData();
        jTable1.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private String csvFile = "src/motorphemployee/data.csv"; //Change depends on the file location of csv file (optional)

        private void loadCSVData() { //CSV File Reader
            // Path to CSV File
    String line = "";
    String cvsSplitBy = ",";

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {

        // Read the header row to get column names
        if ((line = br.readLine()) != null) {
            String[] columns = line.split(cvsSplitBy);
            model.setColumnIdentifiers(columns);
        }

        // Read data rows and add to table
        while ((line = br.readLine()) != null) {
            String[] data = line.split(cvsSplitBy);
            model.addRow(data);
        }                                                                                                       

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading data from CSV file: " + e.getMessage());
    }
}
        
        private void saveCSVData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(csvFile))) {

            // Write the header row
            for (int i = 0; i < model.getColumnCount(); i++) {
                bw.write(model.getColumnName(i));
                if (i < model.getColumnCount() - 1) {
                    bw.write(",");
                }
            }
            bw.newLine();

            // Write data rows
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    bw.write(model.getValueAt(i, j).toString());
                    if (j < model.getColumnCount() - 1) {
                        bw.write(",");
                    }
                }
                bw.newLine();
            }
                
               JOptionPane.showMessageDialog(this, "Saved successfully!");

         } catch (IOException e) {
             e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error saving data to CSV file: " + e.getMessage());
            }
        }
                
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_add = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtphonenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsss = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtphilhealth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpagibig = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtsupervisor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtclothing = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtbasicsalary = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtgrosssemi = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txthourlyrate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txttin = new javax.swing.JTextField();
        button_calculatesalary = new javax.swing.JButton();
        button_cleartext = new javax.swing.JButton();
        leave_overview = new javax.swing.JButton();
        button_information = new javax.swing.JButton();
        button_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_add.setText("Add Employee");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_update.setText("Update Details");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_delete.setBackground(new java.awt.Color(204, 0, 0));
        button_delete.setText("Delete User");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_exit.setText("Exit");
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Birthday", "Address", "Phone Number", "SSS #", "Philhealth #", "TIN #", "Pag-ibig #", "Status", "Position", "Immediate Supervisor", "Basic Salary", "Rice Subsidy", "Phone Allowance", "Clothing Allowance", "Gross Semi-monthly Rate", "Hourly Rate"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Personal Information");

        jLabel2.setText("Employee Number");

        jLabel3.setText("Last Name");

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });

        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });

        jLabel4.setText("First Name");

        jLabel5.setText("Birthday");

        txtbirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbirthdayActionPerformed(evt);
            }
        });

        jLabel6.setText("Phone Number");

        jLabel7.setText("Address");

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Tax Information");

        jLabel9.setText("SSS #:");

        jLabel10.setText("Philhealth #:");

        txtphilhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphilhealthActionPerformed(evt);
            }
        });

        jLabel11.setText("Pagibig #:");

        txtpagibig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagibigActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Employee Position:");

        jLabel13.setText("Status");

        jLabel14.setText("Position");

        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });

        jLabel15.setText("Immediate Supervisor");

        txtsupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupervisorActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Benefits:");

        jLabel17.setText("Rice Subsidy");

        txtrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtriceActionPerformed(evt);
            }
        });
        txtrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtriceKeyPressed(evt);
            }
        });

        jLabel18.setText("Phone Allowance");

        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });

        jLabel19.setText("Clothing Allowance");

        txtclothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclothingActionPerformed(evt);
            }
        });
        txtclothing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclothingKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel20.setText("Salary Information:");

        jLabel21.setText("Basic Salary");

        txtbasicsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbasicsalaryKeyPressed(evt);
            }
        });

        jLabel22.setText("Gross Semi-monthly Rate");

        txtgrosssemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrosssemiActionPerformed(evt);
            }
        });
        txtgrosssemi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgrosssemiKeyPressed(evt);
            }
        });

        jLabel23.setText("Hourly Rate");

        txthourlyrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthourlyrateKeyPressed(evt);
            }
        });

        jLabel24.setText("TIN #:");

        button_calculatesalary.setText("Calculate Salary");
        button_calculatesalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_calculatesalaryActionPerformed(evt);
            }
        });

        button_cleartext.setText("Clear Text");
        button_cleartext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cleartextActionPerformed(evt);
            }
        });

        leave_overview.setText("Leave Overview");
        leave_overview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_overviewActionPerformed(evt);
            }
        });

        button_information.setText("View Information");
        button_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_informationActionPerformed(evt);
            }
        });

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(txtlastname)
                                        .addComponent(txtfirstname)
                                        .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                                        .addComponent(txtphonenumber)
                                        .addComponent(txtbirthday)
                                        .addComponent(txtid)))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsss)
                                    .addComponent(txtphilhealth)
                                    .addComponent(txtposition)
                                    .addComponent(txtsupervisor)
                                    .addComponent(txtpagibig)
                                    .addComponent(txttin)
                                    .addComponent(txtstatus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel24))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16)
                                        .addComponent(txtrice)
                                        .addComponent(jLabel18)
                                        .addComponent(txtphone)
                                        .addComponent(jLabel19)
                                        .addComponent(txtclothing)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21)
                                        .addComponent(txtbasicsalary)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel23)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(txtgrosssemi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txthourlyrate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(button_calculatesalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(leave_overview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(button_cleartext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(button_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_exit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_save)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_cleartext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphilhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpagibig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtclothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtbasicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtgrosssemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthourlyrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button_information)
                            .addGap(31, 31, 31)
                            .addComponent(button_calculatesalary)
                            .addGap(29, 29, 29)
                            .addComponent(button_update)
                            .addGap(26, 26, 26)
                            .addComponent(leave_overview)
                            .addGap(18, 18, 18)
                            .addComponent(button_delete))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttin)
                                .addComponent(txtbirthday))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1460, 868));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:                                         
        if(txtid.getText().isEmpty() || txtaddress.getText().isEmpty() || txtbasicsalary.getText().isEmpty() || txtbirthday.getText().isEmpty() || txtclothing.getText().isEmpty() || txtfirstname.getText().isEmpty() || txtgrosssemi.getText().isEmpty() || txthourlyrate.getText().isEmpty() || txtlastname.getText().isEmpty() || txtpagibig.getText().isEmpty() || txtphilhealth.getText().isEmpty() || txtphone.getText().isEmpty() || txtphonenumber.getText().isEmpty() || txtposition.getText().isEmpty() || txtrice.getText().isEmpty() || txtsss.getText().isEmpty() || txtstatus.getText().isEmpty() || txtsupervisor.getText().isEmpty() || txttin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter All Data");
        } else {
            
            int id = Integer.parseInt(txtid.getText());
            String lastName = txtlastname.getText();
            String firstName = txtfirstname.getText();
            String birthday = txtbirthday.getText();
            String address = txtaddress.getText();
            String phoneNumber = txtphonenumber.getText();
            String sss = txtsss.getText();
            String philhealth = txtphilhealth.getText();
            String tin = txttin.getText();
            String pagibig = txtpagibig.getText();
            String status = txtstatus.getText();
            String position = txtposition.getText();
            String supervisor = txtsupervisor.getText();
            double basicSalary = Double.parseDouble(txtbasicsalary.getText());
            double clothingAllowance = Double.parseDouble(txtclothing.getText());
            double riceSubsidy = Double.parseDouble(txtrice.getText());
            double phoneAllowance = Double.parseDouble(txtphone.getText());
            double grossSemiMonthlyRate = Double.parseDouble(txtgrosssemi.getText());
            double hourlyRate = Double.parseDouble(txthourlyrate.getText());
            
            // Add data to table
            Object[] rowData = { id, lastName, firstName, birthday, address, phoneNumber, sss, philhealth, tin, pagibig, status, position, supervisor, basicSalary, riceSubsidy, phoneAllowance, clothingAllowance, grossSemiMonthlyRate, hourlyRate };
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.addRow(rowData);
}

    }//GEN-LAST:event_button_addActionPerformed

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:                                    
    // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Check if exactly one row is selected
    if (jTable1.getSelectedRowCount() == 1) {
        // Retrieve the updated values from the text fields
        String id = txtid.getText();
        String lastName = txtlastname.getText();
        String firstName = txtfirstname.getText();
        String birthday = txtbirthday.getText();
        String address = txtaddress.getText();
        String phoneNumber = txtphonenumber.getText();
        String sss = txtsss.getText();
        String philhealth = txtphilhealth.getText();
        String tin = txttin.getText();
        String pagibig = txtpagibig.getText();
        String status = txtstatus.getText();
        String position = txtposition.getText();
        String supervisor = txtsupervisor.getText();
        String basicSalary = txtbasicsalary.getText();
        String riceSubsidy = txtrice.getText();
        String phoneAllowance = txtphone.getText();
        String clothingAllowance = txtclothing.getText();
        String grossSemiMonthlyRate = txtgrosssemi.getText( );
        String hourlyRate = txthourlyrate.getText();
        
        // Set the updated values in the selected row
        tblModel.setValueAt(id, jTable1.getSelectedRow(), 0);
        tblModel.setValueAt(lastName, jTable1.getSelectedRow(), 1);
        tblModel.setValueAt(firstName, jTable1.getSelectedRow(), 2);
        tblModel.setValueAt(birthday, jTable1.getSelectedRow(), 3);
        tblModel.setValueAt(address, jTable1.getSelectedRow(), 4);
        tblModel.setValueAt(phoneNumber, jTable1.getSelectedRow(), 5);
        tblModel.setValueAt(sss, jTable1.getSelectedRow(), 6);
        tblModel.setValueAt(philhealth, jTable1.getSelectedRow(), 7);
        tblModel.setValueAt(tin, jTable1.getSelectedRow(), 8);
        tblModel.setValueAt(pagibig, jTable1.getSelectedRow(), 9);
        tblModel.setValueAt(status, jTable1.getSelectedRow(), 10);
        tblModel.setValueAt(position, jTable1.getSelectedRow(), 11);
        tblModel.setValueAt(supervisor, jTable1.getSelectedRow(), 12);
        tblModel.setValueAt(basicSalary, jTable1.getSelectedRow(), 13);
        tblModel.setValueAt(riceSubsidy, jTable1.getSelectedRow(), 14);
        tblModel.setValueAt(phoneAllowance, jTable1.getSelectedRow(), 15);
        tblModel.setValueAt(clothingAllowance, jTable1.getSelectedRow(), 16);
        tblModel.setValueAt(grossSemiMonthlyRate, jTable1.getSelectedRow(), 17);
        tblModel.setValueAt(hourlyRate, jTable1.getSelectedRow(), 18);
        
        //Update message display if successful
        
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
        // Display update message or perform any other necessary actions
    } else {
        if(jTable1.getRowCount () ==0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else{
            JOptionPane.showMessageDialog(this, "Please select Single Row For Update");
        }
    }
    }//GEN-LAST:event_button_updateActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtbirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirthdayActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphilhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphilhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphilhealthActionPerformed

    private void txtpagibigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagibigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagibigActionPerformed

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed

    private void txtsupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupervisorActionPerformed

    private void txtclothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclothingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclothingActionPerformed

    private void txtgrosssemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrosssemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrosssemiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            
    // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalary = tblModel.getValueAt(selectedRowIndex, 13).toString();;
        String riceSubsidy = tblModel.getValueAt(selectedRowIndex, 14).toString();;
        String phoneAllowance = tblModel.getValueAt(selectedRowIndex, 15).toString();;
        String clothingAllowance = tblModel.getValueAt(selectedRowIndex, 16).toString();;
        String grossSemiMonthlyRate = tblModel.getValueAt(selectedRowIndex, 17).toString();;
        String hourlyRate = tblModel.getValueAt(selectedRowIndex, 18).toString();;
        
        // Set retrieved values to text fields
        
        txtid.setText(id);
        txtlastname.setText(lastName);
        txtfirstname.setText(firstName);
        txtbirthday.setText(birthday);
        txtaddress.setText(address);
        txtphonenumber.setText(phoneNumber);
        txtsss.setText(sss);
        txtphilhealth.setText(philhealth);
        txttin.setText(tin);
        txtpagibig.setText(pagibig);
        txtstatus.setText(status);
        txtposition.setText(position);
        txtsupervisor.setText(supervisor);
        txtbasicsalary.setText(basicSalary);
        txtrice.setText(riceSubsidy);
        txtphone.setText(phoneAllowance);
        txtclothing.setText(clothingAllowance);
        txtgrosssemi.setText(grossSemiMonthlyRate);
        txthourlyrate.setText(hourlyRate);   
}
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:                                              
    // Get the selected row count
    int selectedRowCount = jTable1.getSelectedRowCount();
    
    // Check if exactly one row is selected
    if (selectedRowCount == 1) {
        // Prompt the user for confirmation
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected row?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        
        // Check user's response
        if (option == JOptionPane.YES_OPTION) {
            // If user confirms deletion, delete the selected row
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.removeRow(jTable1.getSelectedRow());
        }
    } else {
        if (jTable1.getRowCount() == 0) {
            // If the table is empty, display a message
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            // If multiple rows are selected or no row is selected, display a message
            JOptionPane.showMessageDialog(this, "Please select a single row for deletion.");
        }
    }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_calculatesalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_calculatesalaryActionPerformed
        // TODO add your handling code here:
        // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalaryStr = tblModel.getValueAt(selectedRowIndex, 13).toString();
        String riceSubsidyStr = tblModel.getValueAt(selectedRowIndex, 14).toString();
        String phoneAllowanceStr = tblModel.getValueAt(selectedRowIndex, 15).toString();
        String clothingAllowanceStr = tblModel.getValueAt(selectedRowIndex, 16).toString();
        String grossSemiMonthlyRateStr = tblModel.getValueAt(selectedRowIndex, 17).toString();
        String hourlyRateStr = tblModel.getValueAt(selectedRowIndex, 18).toString();
        
        // Convert string to double
        double hourlyRate = Double.parseDouble(hourlyRateStr);

        // Assuming number of worked days is entered by the user
        int workedDays = 0;
            boolean validInput = false;

            while (!validInput) {
                String input = JOptionPane.showInputDialog("Enter worked days:");
    
                if (input == null) {
                // If the user clicks "Cancel", exit the loop or handle it accordingly
                 JOptionPane.showMessageDialog(null, "Operation cancelled.");
                    return; // Exit the method if in a method, or handle appropriately
             }
    
             try {
                    workedDays = Integer.parseInt(input);
                 if (workedDays <= 0) {
                        JOptionPane.showMessageDialog(null, "Please enter a positive number for worked days.");
                    } else {
                        validInput = true;
                    }
              } catch (NumberFormatException e) {
                 JOptionPane.showMessageDialog(null, "Please enter a valid integer for worked days.");
         }
        }
        // Calculate total salary
        double totalSalary = workedDays * hourlyRate * 8; //Assuming working 8 hours a day

        // Call SSS, PhilHealth, Pagibig methods
        double sssContribution = calculateSSSContribution(totalSalary);
        double philhealthContribution = calculatePhilHealthContribution(totalSalary);
        double pagibigContribution = calculatePagibigContribution(totalSalary);
        
        // Calculate total deductions withouyt WithHolding Tax
        double grossDeductions = sssContribution + philhealthContribution + pagibigContribution;
        
        // Calculate Salary After Tax
        double salaryAfterTax = totalSalary - grossDeductions;
        
        // Call Withholding Tax methods
        double withholdingTax = calculateWithholdingTax(salaryAfterTax);
        
        // Calculate total deductions
        double totalDeductions = grossDeductions + withholdingTax;
        
        // Calculate Net Pay
        double netPay = salaryAfterTax - withholdingTax;
        
        // Display salary and deductions in a dialog
        String message = "Employee: " + firstName + " " + lastName + "\n";
        message += "Worked Days: " + workedDays + "\n";
        message += "Gross Salary: PHP " + String.format("%.2f", totalSalary) + "\n";
        message += "SSS Contribution: PHP " + String.format("%.2f", sssContribution) + "\n";
        message += "PhilHealth Contribution: PHP " + String.format("%.2f", philhealthContribution) + "\n";
        message += "Pagibig Contribution: PHP " + String.format("%.2f", pagibigContribution) + "\n";
        message += "Withholding Tax: PHP " + String.format("%.2f", withholdingTax) + "\n";
        message += "Total Deduction: PHP " +  String.format("%.2f", totalDeductions) + "\n";
        message += "Net Pay: PHP " + String.format("%.2f", netPay) + "\n";

        JOptionPane.showMessageDialog(this, message);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to calculate salary.");
    }
    }//GEN-LAST:event_button_calculatesalaryActionPerformed

    private void button_cleartextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cleartextActionPerformed
        // TODO add your handling code here:
        
    //Clear text
    txtid.setText("");
    txtaddress.setText("");
    txtbasicsalary.setText("");
    txtbirthday.setText("");
    txtclothing.setText("");
    txtfirstname.setText("");
    txtgrosssemi.setText("");
    txthourlyrate.setText("");
    txtlastname.setText("");
    txtpagibig.setText("");
    txtphilhealth.setText("");
    txtphone.setText("");
    txtphonenumber.setText("");
    txtposition.setText("");
    txtrice.setText("");
    txtsss.setText("");
    txtstatus.setText("");
    txtsupervisor.setText("");
    txttin.setText("");
    }//GEN-LAST:event_button_cleartextActionPerformed

    private void txtriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtriceActionPerformed

    private void button_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_informationActionPerformed
        // TODO add your handling code here:
        // Retrieve the table model
    DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
    
    // Get the selected row index
    int selectedRowIndex = jTable1.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRowIndex != -1) {
        // Retrieve values from the selected row
        String id = tblModel.getValueAt(selectedRowIndex, 0).toString();
        String lastName = tblModel.getValueAt(selectedRowIndex, 1).toString();
        String firstName = tblModel.getValueAt(selectedRowIndex, 2).toString();
        String birthday = tblModel.getValueAt(selectedRowIndex, 3).toString();
        String address = tblModel.getValueAt(selectedRowIndex, 4).toString();
        String phoneNumber = tblModel.getValueAt(selectedRowIndex, 5).toString();
        String sss = tblModel.getValueAt(selectedRowIndex, 6).toString();
        String philhealth = tblModel.getValueAt(selectedRowIndex, 7).toString();
        String tin = tblModel.getValueAt(selectedRowIndex, 8).toString();
        String pagibig = tblModel.getValueAt(selectedRowIndex, 9).toString();
        String status = tblModel.getValueAt(selectedRowIndex, 10).toString();
        String position = tblModel.getValueAt(selectedRowIndex, 11).toString();
        String supervisor = tblModel.getValueAt(selectedRowIndex, 12).toString();
        String basicSalary = tblModel.getValueAt(selectedRowIndex, 13).toString();;
        String riceSubsidy = tblModel.getValueAt(selectedRowIndex, 14).toString();;
        String phoneAllowance = tblModel.getValueAt(selectedRowIndex, 15).toString();;
        String clothingAllowance = tblModel.getValueAt(selectedRowIndex, 16).toString();;
        String grossSemiMonthlyRate = tblModel.getValueAt(selectedRowIndex, 17).toString();;
        String hourlyRate = tblModel.getValueAt(selectedRowIndex, 18).toString();;
        
        // Display the information in a dialog
        String message = "Employee ID: " + id + "\n";
        message += "Last Name: " + lastName + "\n";
        message += "First Name: " + firstName + "\n";
        message += "Birthday: " + birthday + "\n";
        message += "Address: " + address + "\n";
        message += "Phone Number: " + phoneNumber + "\n";
        message += "SSS: " + sss + "\n";
        message += "Philhealth: " + philhealth + "\n";
        message += "TIN: " + tin + "\n";
        message += "Pag-ibig: " + pagibig + "\n";
        message += "Status: " + status + "\n";
        message += "Position: " + position + "\n";
        message += "Supervisor: " + supervisor + "\n";
        message += "Basic Salary: " + basicSalary + "\n";
        message += "Rice Subsidy: " + riceSubsidy + "\n";
        message += "Phone Allowance: " + phoneAllowance + "\n";
        message += "Clothing Allowance: " + clothingAllowance + "\n";
        message += "Gross Semi-monthly Rate: " + grossSemiMonthlyRate + "\n";
        message += "Hourly Rate: " + hourlyRate + "\n";
        
        JOptionPane.showMessageDialog(this, message);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to view information.");
    }
    }//GEN-LAST:event_button_informationActionPerformed

    private void leave_overviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_overviewActionPerformed
        // TODO add your handling code here:
        // Will add new function here soon
    }//GEN-LAST:event_leave_overviewActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        saveCSVData();
    }//GEN-LAST:event_button_saveActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE))) {
        txtid.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txtid.setEditable(true); 
        }
    }//GEN-LAST:event_txtidKeyPressed

    private void txtriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtriceKeyPressed
        // TODO add your handling code here:
       char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE))) {
        txtrice.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txtrice.setEditable(true); 
        }
    }//GEN-LAST:event_txtriceKeyPressed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE))) {
        txtphone.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txtphone.setEditable(true); 
        }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void txtclothingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclothingKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE))) {
        txtclothing.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txtclothing.setEditable(true); 
        }
    }//GEN-LAST:event_txtclothingKeyPressed

    private void txtbasicsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbasicsalaryKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_PERIOD))) {
        txtbasicsalary.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txtbasicsalary.setEditable(true); 
        }
    }//GEN-LAST:event_txtbasicsalaryKeyPressed

    private void txtgrosssemiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrosssemiKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_PERIOD))) {
        txtgrosssemi.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txtgrosssemi.setEditable(true); 
        }
    }//GEN-LAST:event_txtgrosssemiKeyPressed

    private void txthourlyrateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthourlyrateKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_PERIOD))) {
        txthourlyrate.setEditable(false);
        JOptionPane.showMessageDialog(null, "Invalid Value, Try Again...");
        getToolkit().beep();
        evt.consume();
        }else{
        txthourlyrate.setEditable(true); 
        }
    }//GEN-LAST:event_txthourlyrateKeyPressed
    // Will transfer this methods on other file soon
    //SSS Method
            public static double calculateSSSContribution(double totalSalary) {
                double sssContribution = 0;
                
                if (totalSalary <= 3250) {
                    sssContribution = 135;
                } else if (totalSalary <= 3750) {
                    sssContribution = 157.50;
                } else if (totalSalary <= 4250) {
                    sssContribution = 180;
                } else if (totalSalary <= 4750) {
                    sssContribution = 202.50;
                } else if (totalSalary <= 5250) {
                    sssContribution = 225;
                } else if (totalSalary <= 5750) {
                    sssContribution = 247.50;
                } else if (totalSalary <= 6250) {
                    sssContribution = 270;
                } else if (totalSalary <= 6750) {
                    sssContribution = 292.50;
                } else if (totalSalary <= 7250) {
                    sssContribution = 315;
                } else if (totalSalary <= 7750) {
                    sssContribution = 337.50;
                } else if (totalSalary <= 8250) {
                    sssContribution = 360;
                } else if (totalSalary <= 8750) {
                    sssContribution = 382.50;
                } else if (totalSalary <= 9250) {
                    sssContribution = 405;
                } else if (totalSalary <= 9750) {
                    sssContribution = 427.50;
                } else if (totalSalary <= 10250) {
                    sssContribution = 450;
                } else if (totalSalary <= 10750) {
                    sssContribution = 472.50;
                } else if (totalSalary <= 11250) {
                    sssContribution = 495;
                } else if (totalSalary <= 11750) {
                    sssContribution = 517.50;
                } else if (totalSalary <= 12250) {
                    sssContribution = 540;
                } else if (totalSalary <= 12750) {
                    sssContribution = 562.50;
                } else if (totalSalary <= 13250) {
                    sssContribution = 585;
                } else if (totalSalary <= 13750) {
                    sssContribution = 607.50;
                } else if (totalSalary <= 14250) {
                    sssContribution = 630;
                } else if (totalSalary <= 14750) {
                    sssContribution = 652.50;
                } else if (totalSalary <= 15250) {
                    sssContribution = 675;
                } else if (totalSalary <= 15750) {
                    sssContribution = 697.50;
                } else if (totalSalary <= 16250) {
                    sssContribution = 720;
                } else if (totalSalary <= 16750) {
                    sssContribution = 742.50;
                } else if (totalSalary <= 17250) {
                    sssContribution = 765;
                } else if (totalSalary <= 17750) {
                    sssContribution = 787.50;
                } else if (totalSalary <= 18250) {
                    sssContribution = 810;
                } else if (totalSalary <= 18750) {
                    sssContribution = 832.50;
                } else if (totalSalary <= 19250) {
                    sssContribution = 855;
                } else if (totalSalary <= 19750) {
                    sssContribution = 877.50;
                } else if (totalSalary <= 20250) {
                    sssContribution = 900;
                } else if (totalSalary <= 20750) {
                    sssContribution = 922.50;
                } else if (totalSalary <= 21250) {
                    sssContribution = 945;
                } else if (totalSalary <= 21750) {
                    sssContribution = 967.50;
                } else if (totalSalary <= 22250) {
                    sssContribution = 990;
                } else if (totalSalary <= 22750) {
                    sssContribution = 1012.50;
                } else if (totalSalary <= 23250) {
                    sssContribution = 1035;
                } else if (totalSalary <= 23750) {
                    sssContribution = 1057.50;
                } else if (totalSalary <= 24250) {
                    sssContribution = 1080;
                } else if (totalSalary <= 24750) {
                    sssContribution = 1102.50;
                } else {
                    sssContribution = 1125;
                }
            
                return sssContribution;
            }

            //Philhealth Method
            public static double calculatePhilHealthContribution(double totalSalary) {
                double premiumRate = 0.03; // 3% Premium Rate
        
                // Calculate monthly premium based on salary range
                double monthlyPremium;
                if (totalSalary <= 10000) {
                    monthlyPremium = 300;
                } else if (totalSalary <= 59999.99) {
                    monthlyPremium = Math.min(300 + (totalSalary - 10000) * premiumRate, 1800);
                } else {
                    monthlyPremium = 1800;
                }
        
                // Employee and employer share equally
                return monthlyPremium;
            }

            //Pagibig Method
            public static double calculatePagibigContribution(double totalSalary) {
                double employeeContributionRate = 0;
                double employerContributionRate = 0;
                double totalContributionRate = 0;
        
                if (totalSalary >= 1000 && totalSalary <= 1500) {
                    employeeContributionRate = 0.01;
                    employerContributionRate = 0.02;
                    totalContributionRate = employeeContributionRate + employerContributionRate;
                } else if (totalSalary > 1500) {
                    employeeContributionRate = 0.02;
                    employerContributionRate = 0.02;
                    totalContributionRate = employeeContributionRate + employerContributionRate;
                }
        
                // Calculate the contribution amount
                double totalContribution = Math.min(totalSalary * totalContributionRate, 100); // Maximum contribution is 100
        
                return totalContribution;
            }

            //Withholding Tax Method
            public static double calculateWithholdingTax(double salaryAfterTax) {
                double withholdingTax = 0;
        
                if (salaryAfterTax <= 20832) {
                    withholdingTax = 0;
                } else if (salaryAfterTax <= 33333) {
                    withholdingTax = (salaryAfterTax - 20832) * 0.20;
                } else if (salaryAfterTax <= 66667) {
                    withholdingTax = 2500 + (salaryAfterTax - 33333) * 0.25;
                } else if (salaryAfterTax <= 166667) {
                    withholdingTax = 10833 + (salaryAfterTax - 66667) * 0.30;
                } else if (salaryAfterTax <= 666667) {
                    withholdingTax = 40833.33 + (salaryAfterTax - 166667) * 0.32;
                } else {
                    withholdingTax = 200833.33 + (salaryAfterTax - 666667) * 0.35;
                }
        
                return withholdingTax;
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_calculatesalary;
    private javax.swing.JButton button_cleartext;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_information;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton leave_overview;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtbasicsalary;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtclothing;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgrosssemi;
    private javax.swing.JTextField txthourlyrate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtpagibig;
    private javax.swing.JTextField txtphilhealth;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtrice;
    private javax.swing.JTextField txtsss;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtsupervisor;
    private javax.swing.JTextField txttin;
    // End of variables declaration//GEN-END:variables
}
